---
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -  id: black
       args: [--line-length=100]
-   repo: git://github.com/pre-commit/mirrors-pylint
    rev: v2.2.2
    hooks:
    -  id: pylint
